Only undefine Rails::Server#log_to_stdout if it's defined
I'm experiencing the following error when I run some Rake tasks that use
`rails_semantic_logger`:

```
NameError: undefined method `log_to_stdout' for class `Rails::Server'
```

I don't quite understand how `log_to_stdout` could be undefined, but
this fixes things for me, and seems to be a valid approach to the issue,
so I thought I'd try to land it upstream, so I can upgrade from v4.6.1.